### ISSUE TITLE
求使用教程

### ISSUE THREAD

**Issue by gghao78** [tzwsoho/auto_snail_lucky#1]
大神这个怎么使用呢，安卓模拟器可以吗

**Comment by tzwsoho** [comment]
没试过模拟器，我是在真机上弄的，现在还没弄好，只有ssl_tool和sign_tool能用

**Comment by clzncu** [comment]
同求教程，直接把文件放入安卓机的文件夹里面吗？如何运行？

**Comment by tzwsoho** [comment]
别急，弄好我会写教程的

**Comment by tzwsoho** [comment]
> 同求教程，直接把文件放入安卓机的文件夹里面吗？如何运行？



> 大神这个怎么使用呢，安卓模拟器可以吗

测过用雷电自带应用市场里面的几羊可以正常使用，我已经把使用方法放出

**Comment by gghao78** [comment]
大神，我模拟器第一次用的时候可以，但是今天再运行的时候点击任意链接，程序毫无响应呢，不往下走

**Comment by tzwsoho** [comment]
@gghao78 是不是你更新了几羊？貌似新版做了防护措施，卸载重装旧版就可以了

**Comment by gghao78** [comment]
现在没问题了，就是想问一下每次执行前都必须先把adb shell里的frida打开再执行python吗

**Comment by tzwsoho** [comment]
@gghao78 是的，因为我的脚本依赖frida-server

**Comment by gghao78** [comment]
我现在想能不能弄个bat批处理，点击后先执行Frida打开的操作然后执行python，但是我没弄好，执行多条cmd指令的时候它打开adb shell后后面写的语句就不执行了

**Comment by tzwsoho** [comment]
@gghao78 试试 adb shell su -c /data/local/tmp/frida-server-xxx
