### ISSUE TITLE
可以添加自选码抽奖吗

### ISSUE THREAD

**Issue by szc-12** [tzwsoho/auto_snail_lucky#10]
随机码就行，看广告太费时间了，这样就又能多一成的中将概率，哈哈。。另外，十分感谢，虽然坚持很久也没中，但是很感谢呀，太省时间了，感谢感谢，等中了大奖，给您发个大红包，嘿嘿o((>ω< ))o

**Comment by historicgracer** [comment]
你弄自选码，我弄指定商品，直接几羊抽奖2.0 pro max plus ultra + 版

**Comment by tzwsoho** [comment]
有段时间没玩了，没留意过这功能，有时间我看看

**Comment by tzwsoho** [comment]
> 随机码就行，看广告太费时间了，这样就又能多一成的中将概率，哈哈。。另外，十分感谢，虽然坚持很久也没中，但是很感谢呀，太省时间了，感谢感谢，等中了大奖，给您发个大红包，嘿嘿o((>ω< ))o

加上了
