### ISSUE TITLE
一个自选码的小问题

### ISSUE THREAD

**Issue by historicgracer** [tzwsoho/auto_snail_lucky#11]
个人收藏抽奖，抽到860个商品左右，就必定出现自选码已存在的失败提示，我收藏了接近900个商品，然后后面剩下的全部自选码都是重复的了，重新运行直接跳过已抽奖的了。

我想问的是自选码避免不了重复吗（我改了下，碰到存在就循环抽。。）

![1643033133(1)](https://user-images.githubusercontent.com/76905524/150797372-3d10e7f0-7bf1-4ebb-9854-c57f19b2efd7.jpg)

**Comment by tzwsoho** [comment]
建议你改一下代码，不要调用获取随机自选码的接口，直接自己生成自选码就可以了

**Comment by historicgracer** [comment]
> 建议你改一下代码，不要调用获取随机自选码的接口，直接自己生成自选码就可以了

这样不就有重复的问题了嘛？虽然自己生成确实可以重复，只是获取随机码这个接口可以判断重复哦

**Comment by historicgracer** [comment]
我判断下吧，存在+1就行了

**Comment by historicgracer** [comment]
那个。。纠正一下，是我的问题，获取商品最大一次20个，所以我20一组循环几十次一次性放一起，因为数组倒了下顺序，数组开头第一组商品获取了两次，不是接口问题，错误信息也没认真看写的意思是商品重复抽了。。。尴尬
![Uploading 捕获.JPG…]()

**Comment by historicgracer** [comment]
那个。。纠正一下，是我的问题，获取商品最大一次20个，所以我20一组循环几十次一次性放一起，因为数组倒了下顺序，数组开头第一组商品获取了两次，不是接口问题，错误信息也没认真看写的意思是商品重复抽了。。。尴尬

**Comment by historicgracer** [comment]
![捕获](https://user-images.githubusercontent.com/76905524/151909869-2e778702-b000-4027-8884-4b99b53c529e.JPG)
