### ISSUE TITLE
无限循环

### ISSUE THREAD

**Issue by LXH112711** [tzwsoho/auto_snail_lucky#13]
![屏幕截图 2022-02-27 141223](https://user-images.githubusercontent.com/98231341/155870699-8cada94d-f72f-4bf1-95e5-d7a8c1636787.png)
在抽400次的时候，不知道为什么会这样无限循环。

**Comment by tzwsoho** [comment]
拉一下新代码

**Comment by historicgracer** [comment]
> 拉一下新代码

更新了什么东西？
另外问下，代码目前有清理失效收藏的动作吗？我把失败删除商品的注释起来了，早些时候跑，连续删除收藏，看着就恐怖。。
如果没有希望能加下，或者原本有的地方在哪，我注释下

**Comment by tzwsoho** [comment]
> 

就是修复了新版几羊无限循环抽奖的问题啊，有清理失效收藏的代码，你搜一下“取消收藏”

**Comment by historicgracer** [comment]
> 拉一下新代码

获取首页的三个宝箱好像没有吧？我在用的是加入自选码那一次的版本

**Comment by tzwsoho** [comment]
> > 拉一下新代码
> 
> 获取首页的三个宝箱好像没有吧？我在用的是加入自选码那一次的版本

收藏商品太多就不会去拉商品列表，这样就不会获得宝箱
