### ISSUE TITLE
单线程化

### ISSUE THREAD

**Issue by huanghe2015** [tzwsoho/auto_snail_lucky#17]
可以考虑等组队码出来之后再进行下一个抽奖。一方面方便保存数据 #16 ，另一方面让操作看起来更自然。

**Comment by historicgracer** [comment]
组队随缘的吧？不是每个抽奖都成功组队的

**Comment by huanghe2015** [comment]
可以等组出来再下一步的

**Comment by tzwsoho** [comment]
> 可以考虑等组队码出来之后再进行下一个抽奖。一方面方便保存数据 #16 ，另一方面让操作看起来更自然。

我就是试过才不那样做，那样抽奖很慢的

**Comment by huanghe2015** [comment]
哦，那没事了。主要是为了保存数据。
