### ISSUE TITLE
python运行出现错误

### ISSUE THREAD

**Issue by gghao78** [tzwsoho/auto_snail_lucky#2]
总是会出现TypeError: argument of type 'NoneType' is not [iterable这样的错误。并且每次运行时错误出现的位置也不一样

 Expecting value: line 1 column 1 (char 0)
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Exception ignored in thread started by: <function on_ready at 0x000001C6297F1C10>
Traceback (most recent call last):
  File "D:\Program Files\Python3.8\AutoScripts\auto_snail_lucky-master\loader.py", line 1226, in on_ready
    if 'lotteryRecordId' in lottery_ret: # 继续进行摇一摇
TypeError: argument of type 'NoneType' is not iterable

**Comment by tzwsoho** [comment]
网络问题，我没加重试机制
