### ISSUE TITLE
希望添加更多功能

### ISSUE THREAD

**Issue by cyist** [tzwsoho/auto_snail_lucky#5]
这里有几个好的想法：
-添加“删除收藏夹内找不到商品信息的商品”
-添加“自定义搜索内容，遍历搜索中的商品并按照价格依次抽奖”
-新版几羊更新了多人团，修复一下多人团无法参加的bug
-收藏夹抽奖过程中每隔一段时间自动收羊毛
-修复一下收藏夹一次没有抽完的bug
（抽中就立马过来给赞助~）

**Comment by tzwsoho** [comment]
> 这里有几个好的想法： -添加“删除收藏夹内找不到商品信息的商品” -添加“自定义搜索内容，遍历搜索中的商品并按照价格依次抽奖” -新版几羊更新了多人团，修复一下多人团无法参加的bug -收藏夹抽奖过程中每隔一段时间自动收羊毛 -修复一下收藏夹一次没有抽完的bug （抽中就立马过来给赞助~）

1.已添加
2.太复杂不考虑做，建议自己收藏相关商品
3.没发现有这个问题
4.已添加
5.跟4其实是同一个功能，已添加

**Comment by cyist** [comment]
膜拜大佬
