### ISSUE TITLE
希望更新搜索商品功能

### ISSUE THREAD

**Issue by historicgracer** [tzwsoho/auto_snail_lucky#9]

**Comment by tzwsoho** [comment]
要做成什么样子？详细一点？

**Comment by historicgracer** [comment]
通过app首页右上角的搜索，抽搜索的指定商品~~中自己想要的才是最开心的；其实是我囤了差不多1000w羊毛卡，手刷是刷不完的，等着抽自己想输入的商品。
当前也只能改改价格范围，改成乱序怕中奖被驳回。
小白没学习接口的使用，即loader.py前1/3左右的代码~~

**Comment by historicgracer** [comment]
通过app首页右上角的搜索，抽搜索的指定商品~~中自己想要的才是最开心的；其实是我囤了差不多1000w羊毛卡，手刷是刷不完的，等着抽自己想输入的商品。
当前也只能改改价格范围，改成乱序怕中奖被驳回。
小白没学习接口的使用，即loader.py前1/3左右的代码~~

**Comment by historicgracer** [comment]
通过app首页右上角的搜索，抽搜索的指定商品中自己想要的才是最开心的；其实是我囤了差不多1000w羊毛卡，手刷是刷不完的，等着抽自己想输入的商品。当前也只能改改价格范围，改成乱序怕中奖被驳回。 小白没学习接口的使用，即loader.py前1/3左右的代码

**Comment by tzwsoho** [comment]
那就算要做这个，你也需要将所有搜出来的商品都搜一遍，然后逐个点抽奖吧

**Comment by historicgracer** [comment]
我不太了解，我猜应该是输入或固定的关键字列表之后，每个关键字搜出来都翻十页商品信息，按道理不应该不能实现。

**Comment by szc-12** [comment]
你就不停的收藏收藏收藏，多简单，哈哈

**Comment by tzwsoho** [comment]
> 我不太了解，我猜应该是输入或固定的关键字列表之后，每个关键字搜出来都翻十页商品信息，按道理不应该不能实现。

有时间我看看

**Comment by tzwsoho** [comment]
这个功能应用场景不多，使用的人比较少，暂不考虑去做，或者你可以参考@szc-12的说法，把搜出来的结果都收藏一遍再去抽奖
